package com.example.gcj.enums;

public enum PolicyKey {
    EXPERT_NATION_SUPPORT_POINT,
    EXPERT_YEAR_EXPERIENCE_POINT,
    EXPERT_YEAR_EXPERIENCE_MAX_FACTOR,
    NUMBER_EXPERT_MATCH,
    BOOKING_PRICE,
    MINUS_TO_CANCEL_BOOKING,
    MINUS_TO_BOOKING,
    MINUS_TO_SEND_NOTIFY_INTERVIEWING,
    MINUS_TO_AUTO_END_BOOKING,
    MINUS_TO_CREATE_AVAILABILITY,
    MINUS_BEFORE_APPROVE_BOOKING,
    MINUS_TO_VALID_AVAILABILITY,
    MINUS_TO_AUTO_CANCEL_TRANSACTION, MINUS_TO_AUTO_COMPLETE_BOOKING,
    DURATION_BOOKING_MIN,
    MONEY_BOOKING_PAY_FOR_EXPERT, REVENUE_PERCENT, DEFAULT_EXPERT_POINT, DURATION_BOOKING_MAX
}
