package com.example.gcj.enums;

public enum PolicyKey {
    EXPERT_NATION_SUPPORT_POINT,
    EXPERT_YEAR_EXPERIENCE_POINT,
    EXPERT_YEAR_EXPERIENCE_MAX_FACTOR,
    NUMBER_EXPERT_MATCH,
    BOOKING_PRICE,
    DAY_TO_CANCEL_BOOKING,
    DAY_TO_BOOKING
}
