package com.example.gcj.Shared.enums;

public enum PolicyKey {
    EXPERT_NATION_SUPPORT_POINT,
    EXPERT_YEAR_EXPERIENCE_POINT,
    EXPERT_YEAR_EXPERIENCE_MAX_FACTOR,
    NUMBER_EXPERT_MATCH,
    BOOKING_PRICE,
    MINUS_TO_CANCEL_BOOKING,
    MINUS_TO_BOOKING,
    MINUS_TO_SEND_NOTIFY_INTERVIEWING,
    MINUS_TO_AUTO_END_BOOKING,
    MINUS_TO_CREATE_AVAILABILITY,
    MINUS_BEFORE_APPROVE_BOOKING,
    MINUS_TO_VALID_AVAILABILITY,
    MINUS_TO_AUTO_CANCEL_TRANSACTION, MINUS_TO_AUTO_COMPLETE_BOOKING,
    DURATION_BOOKING_MIN,
    MONEY_BOOKING_PAY_FOR_EXPERT, REVENUE_PERCENT, DEFAULT_EXPERT_POINT, EXPERT_COST_MIN, EXPERT_COST_MAX, NUMBER_RELATE_BLOG, WITHDRAW_MIN, EXPERT_POINT_WHEN_REJECT_BOOKING, EXPERT_POINT_WHEN_CANCEL_BOOKING, EXPERT_POINT_WHEN_COMPLETE_BOOKING, EXPERT_POINT_WHEN_HAVE_GOOD_FEEDBACK, EXPERT_POINT_WHEN_REPORT_EXPERT, EXPERT_SKILL_POINT, EXPERT_PERSONAL_POINT, EXPERT_PERSONAL_POINT_MIN_TO_MATCHING, DURATION_BOOKING_MAX
}
